### ISSUE TITLE
<Magick++.h> not found when brew installing nin10kit

### ISSUE THREAD

**Issue by WilliamYuhangLee** [TricksterGuy/nin10kit#28] opened 2018-11-13 11:00 UTC
Error log as follow:

```
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/ds-exporter.cpp:4:
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/alltypes.hpp:4:
/tmp/nin10kit-20181113-63174-19k2sd5/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/gba-exporter.cpp:4:
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/alltypes.hpp:4:
/tmp/nin10kit-20181113-63174-19k2sd5/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/ds-exporter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/gba-exporter.cpp.o] Error 1
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/3ds-exporter.cpp:5:
In file included from /tmp/nin10kit-20181113-63174-19k2sd5/shared/export_params.hpp:6:
/tmp/nin10kit-20181113-63174-19k2sd5/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/3ds-exporter.cpp.o] Error 1
make[1]: *** [CMakeFiles/shared_files.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cgokmen** [comment] 2018-11-13 17:41
You need to install ImageMagick

**Comment by TricksterGuy** [comment] 2018-11-13 18:36
MAC PROBLEM

**Comment by TricksterGuy** [comment] 2018-11-13 18:37
But yeah install imagemagick

**Comment by cgokmen** [comment] 2018-11-13 18:48
Ouch I missed the title, didn't realize this is a Mac issue - in that case this is a problem with my formula.

@WilliamYuhangLee what version of macOS are you on? Can you show me the full output of brew install? Is imagemagick installing okay? I tried installing just now and it worked fine so I'm unable to reproduce.

**Comment by WilliamYuhangLee** [comment] 2018-11-14 05:13
@skyman @TricksterGuy 
I am using the latest macOS Mojave. I tried installing imagemagick and it worked fine. However I still get the <Magick++.h> not found error when making. 

Here is the full output of "brew install skyman/gt/nin10kit":
```
==> Installing nin10kit from skyman/gt
==> Cloning https://github.com/TricksterGuy/nin10kit.git
Updating /Users/WilliamLee/Library/Caches/Homebrew/nin10kit--git
==> Checking out tag 1.7
HEAD is now at 577b9a6 Remove dead code
HEAD is now at 577b9a6 Remove dead code
==> cmake -DENABLE_MAGICK7_SUPPORT=ON .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAK
==> make
Last 15 lines from /Users/WilliamLee/Library/Logs/Homebrew/nin10kit/02.make:
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/ds-exporter.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/gba-exporter.cpp.o] Error 1
In file included from /tmp/nin10kit-20181114-70546-1v0y96e/shared/3ds-exporter.cpp:5:
In file included from /tmp/nin10kit-20181114-70546-1v0y96e/shared/export_params.hpp:6:
/tmp/nin10kit-20181114-70546-1v0y96e/shared/image32.hpp:4:10: fatal error: 'Magick++.h' file not found
#include <Magick++.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/shared_files.dir/shared/3ds-exporter.cpp.o] Error 1
make[1]: *** [CMakeFiles/shared_files.dir/all] Error 2
make: *** [all] Error 2

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/skyman/homebrew-gt/issues
```

And the full error section of the "02.make" file mentioned was pasted in my initial comment.

**Comment by TricksterGuy** [comment] 2018-11-14 05:15
_If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/skyman/homebrew-gt/issues_

would like a moment of your time

**Comment by WilliamYuhangLee** [comment] 2018-11-14 05:25
@TricksterGuy Ok and then I found the same issue but closed and unresolved:
[https://github.com/skyman/homebrew-gt/issues/2](https://github.com/skyman/homebrew-gt/issues/2)

**Comment by TricksterGuy** [comment] 2018-11-14 05:29
Well can you locate where Magick++.h is?

Also not equipped to do anything about this.

**Comment by cgokmen** [comment] 2018-11-14 05:35
Try: `brew link --force imagemagick`

Are you a CS2110 student? If so, come see me during office hours tomorrow at 11am

**Comment by WilliamYuhangLee** [comment] 2018-11-14 05:46
@TricksterGuy @skyman 
I found this issue [ImageMagick (no Magick++.h)??](https://github.com/Homebrew/legacy-homebrew/issues/13559) and installed GraphicsMagick and still couldn't find the Magick++ header file.

And yes I am, will pay a visit as soon as I am done with an exam.

**Comment by TricksterGuy** [comment] 2018-11-14 05:50
Please don't use GraphicsMagick, I have no idea if the program would work linked to GraphicsMagick and GM appears to be forked off an older version of ImageMagick.

Magick++.h comes installed when installing Magick++ from ImageMagick which nin10kit uses.

That issue has a suggestion to run this command.

"Try brew install imagemagick --with-magick-plus-plus."

**Comment by TricksterGuy** [comment] 2018-11-14 05:54
Seems like that may not work.

Yeah don't use GraphicsMagick I don't know if it is API compatible with current version of ImageMagick

**Comment by WilliamYuhangLee** [comment] 2018-11-14 05:54
@TricksterGuy I tried that command too and turned out it wasn't even an available option.

**Comment by cgokmen** [comment] 2018-11-14 15:31
@WilliamYuhangLee I just realized that I have to cancel my office hours today - I’ll try to figure out the problem later today when I have time. Sorry for not being able to see you in person today

**Comment by TricksterGuy** [comment] 2018-11-14 17:09
inb4 Daniel Docker

Docker

But yeah I'd want a fix for this.

Maybe would want a service to build binaries for each system automatically. without having to build it yourself

**Comment by TricksterGuy** [comment] 2018-11-24 08:28
I'm going to close this and further comments should be made in skyman/homebrew-gt#2

**Closed as completed by TricksterGuy** 2018-11-24 08:28 UTC
